print("i will now count my chickens:")
print("hens",25+30/6)
print("now i will count the eggs:")
print(3+2+1-5+4%2-1/4+6)
print("is it true that 3+2<5-7?")
print(3+2<5-7)
print("what is 3+2?",3+2)
print("what is 5-7?",5-7)
print("oh, that's why it's false")
print("who about some more")
print("is it greater?",5>-2)
print("is it greater or equal?",5>=-2)
print("it is less or equal?",5<=-2)